package main

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"
)

type server struct { db *pgxpool.Pool }
type resourceView struct { ID string `json:"id"`; Type string `json:"type"`; Name string `json:"name"`; Status string `json:"status"`; Managed bool `json:"managed"`; Source string `json:"source"`; Metadata map[string]any `json:"metadata"`; Metrics map[string]any `json:"metrics,omitempty"`; LastSeen *time.Time `json:"last_seen,omitempty"` }

func main(){
	ctx:=context.Background(); dsn:=env("DATABASE_URL","postgres://homelab:homelab@localhost:5432/homelab?sslmode=disable"); pool,err:=pgxpool.New(ctx,dsn); if err!=nil{log.Fatal(err)}; defer pool.Close()
	for i:=0;i<30;i++{if err=pool.Ping(ctx);err==nil{break};log.Printf("waiting for database: %v",err);time.Sleep(2*time.Second)};if err!=nil{log.Fatalf("database unavailable: %v",err)};if err:=migrate(ctx,pool);err!=nil{log.Fatalf("migration failed: %v",err)}
	s:=&server{db:pool};mux:=http.NewServeMux();mux.HandleFunc("GET /api/v1/health",s.health);mux.HandleFunc("GET /api/v1/setup/status",s.setupStatus);mux.HandleFunc("POST /api/v1/setup/owner",s.setupOwner);mux.HandleFunc("POST /api/v1/auth/login",s.login);mux.Handle("GET /api/v1/dashboard",s.requireAuth(http.HandlerFunc(s.dashboard)));mux.Handle("GET /api/v1/resources",s.requireAuth(http.HandlerFunc(s.resources)));mux.Handle("GET /api/v1/topology",s.requireAuth(http.HandlerFunc(s.topology)));mux.Handle("POST /api/v1/enrolment-tokens",s.requireAuth(http.HandlerFunc(s.createEnrolmentToken)));mux.HandleFunc("POST /api/v1/agent/enrol",s.agentEnrol);mux.HandleFunc("POST /api/v1/agent/heartbeat",s.agentHeartbeat)
	addr:=env("LISTEN_ADDR",":8080");log.Printf("hcp api listening on %s",addr);log.Fatal(http.ListenAndServe(addr,requestLogger(mux)))
}

func migrate(ctx context.Context,db *pgxpool.Pool)error{const schema=`
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash BYTEA NOT NULL,role TEXT NOT NULL DEFAULT 'owner',created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS resources (id TEXT PRIMARY KEY,type TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'unknown',managed BOOLEAN NOT NULL DEFAULT false,source TEXT NOT NULL DEFAULT 'manual',external_id TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS resources_source_external_idx ON resources(source,external_id) WHERE external_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS agents (resource_id TEXT PRIMARY KEY REFERENCES resources(id) ON DELETE CASCADE,secret_hash TEXT NOT NULL,version TEXT NOT NULL DEFAULT '',last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS metrics_latest (resource_id TEXT PRIMARY KEY REFERENCES resources(id) ON DELETE CASCADE,cpu_percent DOUBLE PRECISION NOT NULL DEFAULT 0,memory_percent DOUBLE PRECISION NOT NULL DEFAULT 0,disk_percent DOUBLE PRECISION NOT NULL DEFAULT 0,load1 DOUBLE PRECISION NOT NULL DEFAULT 0,uptime_seconds BIGINT NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS relationships (id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,target_id TEXT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,kind TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(source_id,target_id,kind));
CREATE TABLE IF NOT EXISTS enrolment_tokens (token_hash TEXT PRIMARY KEY,created_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS activity (id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,resource_id TEXT,detail JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());`;_,err:=db.Exec(ctx,schema);return err}

func(s *server)health(w http.ResponseWriter,r *http.Request){if err:=s.db.Ping(r.Context());err!=nil{writeJSON(w,http.StatusServiceUnavailable,map[string]any{"ok":false,"database":false});return};writeJSON(w,200,map[string]any{"ok":true,"database":true,"version":"0.1.0-dev"})}
func(s *server)setupStatus(w http.ResponseWriter,r *http.Request){var count int;if err:=s.db.QueryRow(r.Context(),"SELECT count(*) FROM users").Scan(&count);err!=nil{writeError(w,500,err);return};writeJSON(w,200,map[string]any{"needs_setup":count==0})}
func(s *server)setupOwner(w http.ResponseWriter,r *http.Request){var in struct{Username string `json:"username"`;Password string `json:"password"`};if err:=decodeJSON(r,&in);err!=nil{writeError(w,400,err);return};in.Username=strings.TrimSpace(in.Username);if len(in.Username)<3||len(in.Password)<10{writeJSON(w,400,map[string]any{"error":"username must be at least 3 characters and password at least 10"});return};tx,err:=s.db.Begin(r.Context());if err!=nil{writeError(w,500,err);return};defer tx.Rollback(r.Context());var count int;if err:=tx.QueryRow(r.Context(),"SELECT count(*) FROM users").Scan(&count);err!=nil||count!=0{writeJSON(w,409,map[string]any{"error":"setup already completed"});return};hash,err:=bcrypt.GenerateFromPassword([]byte(in.Password),bcrypt.DefaultCost);if err!=nil{writeError(w,500,err);return};uid:=newID("usr");if _,err:=tx.Exec(r.Context(),"INSERT INTO users(id,username,password_hash,role) VALUES($1,$2,$3,'owner')",uid,in.Username,hash);err!=nil{writeError(w,500,err);return};if err:=tx.Commit(r.Context());err!=nil{writeError(w,500,err);return};token,err:=s.newSession(r.Context(),uid);if err!=nil{writeError(w,500,err);return};writeJSON(w,201,map[string]any{"token":token,"user":map[string]any{"id":uid,"username":in.Username,"role":"owner"}})}
func(s *server)login(w http.ResponseWriter,r *http.Request){var in struct{Username string `json:"username"`;Password string `json:"password"`};if err:=decodeJSON(r,&in);err!=nil{writeError(w,400,err);return};var id,username,role string;var passwordHash []byte;err:=s.db.QueryRow(r.Context(),"SELECT id,username,password_hash,role FROM users WHERE lower(username)=lower($1)",strings.TrimSpace(in.Username)).Scan(&id,&username,&passwordHash,&role);if err!=nil||bcrypt.CompareHashAndPassword(passwordHash,[]byte(in.Password))!=nil{writeJSON(w,401,map[string]any{"error":"invalid username or password"});return};token,err:=s.newSession(r.Context(),id);if err!=nil{writeError(w,500,err);return};writeJSON(w,200,map[string]any{"token":token,"user":map[string]any{"id":id,"username":username,"role":role}})}
func(s *server)newSession(ctx context.Context,userID string)(string,error){token:=newToken(32);_,err:=s.db.Exec(ctx,"INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '30 days')",hashToken(token),userID);return token,err}

type userKey struct{};type authUser struct{ID,Username,Role string}
func(s *server)requireAuth(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){token:=bearer(r.Header.Get("Authorization"));if token==""{writeJSON(w,401,map[string]any{"error":"authentication required"});return};var uid,username,role string;err:=s.db.QueryRow(r.Context(),`SELECT u.id,u.username,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND s.last_seen_at>now()-interval '24 hours'`,hashToken(token)).Scan(&uid,&username,&role);if err!=nil{writeJSON(w,401,map[string]any{"error":"session expired"});return};_,_=s.db.Exec(r.Context(),"UPDATE sessions SET last_seen_at=now() WHERE token_hash=$1",hashToken(token));ctx:=context.WithValue(r.Context(),userKey{},authUser{ID:uid,Username:username,Role:role});next.ServeHTTP(w,r.WithContext(ctx))})}
func(s *server)dashboard(w http.ResponseWriter,r *http.Request){rows,err:=s.db.Query(r.Context(),"SELECT type,count(*) FROM resources GROUP BY type");if err!=nil{writeError(w,500,err);return};defer rows.Close();counts:=map[string]int{};total:=0;for rows.Next(){var typ string;var n int;_=rows.Scan(&typ,&n);counts[typ]=n;total+=n};var online,warnings int;_=s.db.QueryRow(r.Context(),"SELECT count(*) FROM agents WHERE last_seen_at>now()-interval '90 seconds'").Scan(&online);_=s.db.QueryRow(r.Context(),"SELECT count(*) FROM metrics_latest WHERE disk_percent>=85 OR memory_percent>=90").Scan(&warnings);health:=100;if total>0&&warnings>0{health=100-min(warnings*8,60)};writeJSON(w,200,map[string]any{"health":health,"resources":total,"online_agents":online,"warnings":warnings,"counts":counts})}
func(s *server)resources(w http.ResponseWriter,r *http.Request){rows,err:=s.db.Query(r.Context(),`SELECT r.id,r.type,r.name,CASE WHEN a.resource_id IS NOT NULL AND a.last_seen_at<now()-interval '90 seconds' THEN 'offline' ELSE r.status END,r.managed,r.source,r.metadata,m.cpu_percent,m.memory_percent,m.disk_percent,m.load1,m.uptime_seconds,a.last_seen_at FROM resources r LEFT JOIN agents a ON a.resource_id=r.id LEFT JOIN metrics_latest m ON m.resource_id=r.id ORDER BY r.name`);if err!=nil{writeError(w,500,err);return};defer rows.Close();out:=[]resourceView{};for rows.Next(){var v resourceView;var metadata []byte;var cpu,mem,disk,load *float64;var uptime *int64;if err:=rows.Scan(&v.ID,&v.Type,&v.Name,&v.Status,&v.Managed,&v.Source,&metadata,&cpu,&mem,&disk,&load,&uptime,&v.LastSeen);err!=nil{writeError(w,500,err);return};_=json.Unmarshal(metadata,&v.Metadata);if cpu!=nil{v.Metrics=map[string]any{"cpu_percent":*cpu,"memory_percent":derefFloat(mem),"disk_percent":derefFloat(disk),"load1":derefFloat(load),"uptime_seconds":derefInt(uptime)}};out=append(out,v)};writeJSON(w,200,out)}
func(s *server)topology(w http.ResponseWriter,r *http.Request){res:=[]map[string]any{};rows,err:=s.db.Query(r.Context(),"SELECT id,type,name,status,managed FROM resources ORDER BY name");if err!=nil{writeError(w,500,err);return};for rows.Next(){var id,typ,name,status string;var managed bool;_=rows.Scan(&id,&typ,&name,&status,&managed);res=append(res,map[string]any{"id":id,"type":typ,"name":name,"status":status,"managed":managed})};rows.Close();edges:=[]map[string]any{};erows,err:=s.db.Query(r.Context(),"SELECT id,source_id,target_id,kind FROM relationships");if err==nil{defer erows.Close();for erows.Next(){var id,source,target,kind string;_=erows.Scan(&id,&source,&target,&kind);edges=append(edges,map[string]any{"id":id,"source":source,"target":target,"kind":kind})}};writeJSON(w,200,map[string]any{"nodes":res,"edges":edges})}
func(s *server)createEnrolmentToken(w http.ResponseWriter,r *http.Request){u:=r.Context().Value(userKey{}).(authUser);token:=newToken(24);expires:=time.Now().Add(20*time.Minute);if _,err:=s.db.Exec(r.Context(),"INSERT INTO enrolment_tokens(token_hash,created_by,expires_at) VALUES($1,$2,$3)",hashToken(token),u.ID,expires);err!=nil{writeError(w,500,err);return};writeJSON(w,201,map[string]any{"token":token,"expires_at":expires})}
func(s *server)agentEnrol(w http.ResponseWriter,r *http.Request){var in struct{Token string `json:"token"`;Hostname string `json:"hostname"`;OS string `json:"os"`;Arch string `json:"arch"`;MachineID string `json:"machine_id"`;Version string `json:"version"`;IPs []string `json:"ips"`;MACs []string `json:"macs"`;Capabilities map[string]any `json:"capabilities"`};if err:=decodeJSON(r,&in);err!=nil{writeError(w,400,err);return};if in.Token==""||in.Hostname==""||in.MachineID==""{writeJSON(w,400,map[string]any{"error":"token, hostname and machine_id are required"});return};tx,err:=s.db.Begin(r.Context());if err!=nil{writeError(w,500,err);return};defer tx.Rollback(r.Context());var createdBy string;err=tx.QueryRow(r.Context(),`UPDATE enrolment_tokens SET used_at=now() WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now() RETURNING created_by`,hashToken(in.Token)).Scan(&createdBy);if err!=nil{writeJSON(w,401,map[string]any{"error":"invalid, expired or already-used enrolment token"});return};metadata,_:=json.Marshal(map[string]any{"os":in.OS,"arch":in.Arch,"machine_id":in.MachineID,"ips":in.IPs,"macs":in.MACs,"capabilities":in.Capabilities});var rid string;err=tx.QueryRow(r.Context(),"SELECT id FROM resources WHERE source='agent' AND external_id=$1",in.MachineID).Scan(&rid);if errors.Is(err,pgx.ErrNoRows){rid=newID("res");_,err=tx.Exec(r.Context(),`INSERT INTO resources(id,type,name,status,managed,source,external_id,metadata) VALUES($1,'physical_host',$2,'online',true,'agent',$3,$4)`,rid,in.Hostname,in.MachineID,metadata)}else if err==nil{_,err=tx.Exec(r.Context(),"UPDATE resources SET name=$2,status='online',managed=true,metadata=$3,updated_at=now() WHERE id=$1",rid,in.Hostname,metadata)};if err!=nil{writeError(w,500,err);return};secret:=newToken(32);_,err=tx.Exec(r.Context(),`INSERT INTO agents(resource_id,secret_hash,version,last_seen_at) VALUES($1,$2,$3,now()) ON CONFLICT(resource_id) DO UPDATE SET secret_hash=excluded.secret_hash,version=excluded.version,last_seen_at=now()`,rid,hashToken(secret),in.Version);if err!=nil{writeError(w,500,err);return};_,_=tx.Exec(r.Context(),"INSERT INTO activity(id,actor,action,resource_id,detail) VALUES($1,$2,'agent_enrolled',$3,'{}')",newID("act"),"user:"+createdBy,rid);if err:=tx.Commit(r.Context());err!=nil{writeError(w,500,err);return};writeJSON(w,201,map[string]any{"resource_id":rid,"agent_secret":secret})}
func(s *server)agentHeartbeat(w http.ResponseWriter,r *http.Request){rid:=strings.TrimSpace(r.Header.Get("X-Agent-ID"));secret:=bearer(r.Header.Get("Authorization"));if rid==""||secret==""{writeJSON(w,401,map[string]any{"error":"agent authentication required"});return};var stored string;if err:=s.db.QueryRow(r.Context(),"SELECT secret_hash FROM agents WHERE resource_id=$1",rid).Scan(&stored);err!=nil||stored!=hashToken(secret){writeJSON(w,401,map[string]any{"error":"invalid agent credentials"});return};var in struct{CPUPercent float64 `json:"cpu_percent"`;MemoryPercent float64 `json:"memory_percent"`;DiskPercent float64 `json:"disk_percent"`;Load1 float64 `json:"load1"`;UptimeSeconds int64 `json:"uptime_seconds"`;Version string `json:"version"`};if err:=decodeJSON(r,&in);err!=nil{writeError(w,400,err);return};tx,err:=s.db.Begin(r.Context());if err!=nil{writeError(w,500,err);return};defer tx.Rollback(r.Context());_,_=tx.Exec(r.Context(),"UPDATE agents SET last_seen_at=now(),version=$2 WHERE resource_id=$1",rid,in.Version);_,_=tx.Exec(r.Context(),"UPDATE resources SET status='online',updated_at=now() WHERE id=$1",rid);_,err=tx.Exec(r.Context(),`INSERT INTO metrics_latest(resource_id,cpu_percent,memory_percent,disk_percent,load1,uptime_seconds,updated_at) VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT(resource_id) DO UPDATE SET cpu_percent=excluded.cpu_percent,memory_percent=excluded.memory_percent,disk_percent=excluded.disk_percent,load1=excluded.load1,uptime_seconds=excluded.uptime_seconds,updated_at=now()`,rid,clamp(in.CPUPercent),clamp(in.MemoryPercent),clamp(in.DiskPercent),in.Load1,in.UptimeSeconds);if err!=nil{writeError(w,500,err);return};if err:=tx.Commit(r.Context());err!=nil{writeError(w,500,err);return};writeJSON(w,200,map[string]any{"ok":true})}

func requestLogger(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){start:=time.Now();next.ServeHTTP(w,r);log.Printf("%s %s %s",r.Method,r.URL.Path,time.Since(start).Round(time.Millisecond))})}
func decodeJSON(r *http.Request,dst any)error{defer r.Body.Close();dec:=json.NewDecoder(io.LimitReader(r.Body,1<<20));dec.DisallowUnknownFields();return dec.Decode(dst)}
func writeJSON(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_=json.NewEncoder(w).Encode(v)}
func writeError(w http.ResponseWriter,status int,err error){log.Printf("request error: %v",err);writeJSON(w,status,map[string]any{"error":http.StatusText(status)})}
func newID(prefix string)string{return prefix+"_"+newToken(12)}
func newToken(n int)string{b:=make([]byte,n);if _,err:=rand.Read(b);err!=nil{panic(err)};return hex.EncodeToString(b)}
func hashToken(v string)string{s:=sha256.Sum256([]byte(v));return hex.EncodeToString(s[:])}
func bearer(v string)string{if strings.HasPrefix(v,"Bearer "){return strings.TrimSpace(strings.TrimPrefix(v,"Bearer "))};return ""}
func env(k,d string)string{if v:=os.Getenv(k);v!=""{return v};return d}
func clamp(v float64)float64{if v<0{return 0};if v>100{return 100};return v}
func derefFloat(v *float64)float64{if v==nil{return 0};return *v}
func derefInt(v *int64)int64{if v==nil{return 0};return *v}
func min(a,b int)int{if a<b{return a};return b}
